knp_paginator:
  page_range: 5 # Number of links to display in the pagination bar
  default_options:
    page_name: page # Name of the query parameter used for pagination
    sort_field_name: sort # Name of the query parameter used for sorting
    sort_direction_name: direction # Name of the query parameter used for sorting direction
  template:
    pagination: "components/_pagination.html.twig" # template
    sortable : "@KnpPaginator/Pagination/sortable_link.html.twig" #sort link template
    filtration : "@KnpPaginator/Pagination/filtration.html.twig" #filters template